BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes*/*.bb \
            ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-WiFi"
BBFILE_PATTERN_meta-WiFi = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-WiFi = "10"
LAYERSERIES_COMPAT_meta-WiFi = "kirkstone"

